### ISSUE TITLE
Stuck with obscure error "Error: initializing dev environment: creating k8s clients" again

### ISSUE THREAD

**Issue by bentito** [package-operator/package-operator#83]
I tried setting my `CONTAINER_RUNTIME=podman`. This works with a non-dev-mode deploy. But then I set it back to docker. This is failing and I really can't tell what in `GoInstall(kind)` is dying...
```sh
package-operator main $ ./mage dev:deploy
Running target: Dev:Deploy
Running dependency: main.Dev.Load
Running dependency: main.Dev.Setup
Running dependency: main.Dev.init
Running dependency: determineContainerRuntime
Running dependency: main.Dependency.Kind
Error: initializing dev environment: creating k8s clients: creating new ctrl client: Get "https://127.0.0.1:54458/api?timeout=32s": dial tcp 127.0.0.1:54458: connect: connection refused
```

Any ideas on what's wrong or what to do to debug?

**Comment by thetechnick** [comment]
I think this is what is happening:
- there is an existing `package-operator-dev` on docker kind
- CONTAINER_RUNTIME=podman ./mage dev:deploy created a new `package-operator-dev` on podman kind and (over)wrote the kubeconfig to `.cache/dev-env/kubeconfig.yaml`
- going back to docker didn't write to the kubeconfig again, so you are seeing this issue.

Can you teardown the docker-cluster to recreate the kubeconfig file?
`./mage dev:teardown && ./mage dev:deploy`

**Comment by bentito** [comment]
That got a lot farther, but ultimately failed like this:

```bash
package-operator main $ ./mage dev:teardown && ./mage dev:deploy
Running target: Dev:Teardown
Running dependency: main.Dev.init
Running dependency: determineContainerRuntime
2022/11/30 19:24:17 "level"=0 "msg"="detected container-runtime" "container-runtime"="podman"
Running dependency: main.Dependency.Kind
exec: go "install" "sigs.k8s.io/kind@v0.16.0"
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Deleting cluster "package-operator-dev" ...
Running target: Dev:Deploy
Running dependency: main.Dev.Load
Running dependency: main.Dev.Setup
Running dependency: main.Dev.init
Running dependency: determineContainerRuntime
2022/11/30 19:24:18 "level"=0 "msg"="detected container-runtime" "container-runtime"="podman"
Running dependency: main.Dependency.Kind
exec: go "install" "sigs.k8s.io/kind@v0.16.0"
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Creating cluster "package-operator-dev" ...
 ✓ Ensuring node image (kindest/node:v1.25.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-package-operator-dev"
You can now use your cluster with:

kubectl cluster-info --context kind-package-operator-dev --kubeconfig /Users/btofel/workspace/package-operator/.cache/dev-env/kubeconfig.yaml

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
Running dependency: main.Dev.LoadImage
Running dependency: main.Dev.LoadImage
Running dependency: main.Dev.LoadImage
Running dependency: main.Build.Image
Running dependency: main.Build.Image
Running dependency: main.(*builder).Image-fm
Running dependency: main.Build.Image
Running dependency: main.Dev.LoadImage
Running dependency: main.(*builder).init-fm
Running dependency: main.(*builder).Image-fm
Running dependency: main.Dev.LoadImage
Running dependency: main.Build.Image
Running dependency: main.Build.Image
Running dependency: main.(*builder).Image-fm
Running dependency: main.Dev.LoadImage
Running dependency: main.(*builder).Image-fm
Running dependency: main.(*builder).Image-fm
Running dependency: main.Build.Image
Running dependency: main.(*builder).Image-fm
Running dependency: main.Generate.PackageOperatorPackage
Running dependency: main.(*builder).Cmd-fm
Running dependency: main.(*builder).Cmd-fm
Running dependency: main.(*builder).Cmd-fm
Running dependency: main.(*builder).Cmd-fm
exec: go "build" "--ldflags" "-w -s --extldflags '-zrelro -znow -O1'" "--trimpath" "--mod=readonly" "-v" "-o" "bin/linux_amd64/test-stub" "./cmd/test-stub"
exec: go "build" "--ldflags" "-w -s --extldflags '-zrelro -znow -O1'" "--trimpath" "--mod=readonly" "-v" "-o" "bin/linux_amd64/package-operator-manager" "./cmd/package-operator-manager"
exec: go "build" "--ldflags" "-w -s --extldflags '-zrelro -znow -O1'" "--trimpath" "--mod=readonly" "-v" "-o" "bin/linux_amd64/package-operator-webhook" "./cmd/package-operator-webhook"
exec: go "build" "--ldflags" "-w -s --extldflags '-zrelro -znow -O1'" "--trimpath" "--mod=readonly" "-v" "-o" "bin/linux_amd64/remote-phase-manager" "./cmd/remote-phase-manager"
exec: cp "-a" "config/packages/test-stub/." "/Users/btofel/workspace/package-operator/.cache/image/test-stub-package/"
exec: cp "-a" "config/images/package.Containerfile" "/Users/btofel/workspace/package-operator/.cache/image/test-stub-package/Containerfile"
exec: cp "-a" "config/packages/package-operator/." "/Users/btofel/workspace/package-operator/.cache/image/package-operator-package/"
exec: cp "-a" "config/images/package.Containerfile" "/Users/btofel/workspace/package-operator/.cache/image/package-operator-package/Containerfile"
exec: cp "-a" "bin/linux_amd64/test-stub" "/Users/btofel/workspace/package-operator/.cache/image/test-stub/test-stub"
exec: cp "-a" "config/images/test-stub.Containerfile" "/Users/btofel/workspace/package-operator/.cache/image/test-stub/Containerfile"
exec: cp "-a" "config/images/passwd" "/Users/btofel/workspace/package-operator/.cache/image/test-stub/passwd"
exec: cp "-a" "bin/linux_amd64/remote-phase-manager" "/Users/btofel/workspace/package-operator/.cache/image/remote-phase-manager/remote-phase-manager"
exec: cp "-a" "bin/linux_amd64/package-operator-webhook" "/Users/btofel/workspace/package-operator/.cache/image/package-operator-webhook/package-operator-webhook"
exec: cp "-a" "bin/linux_amd64/package-operator-manager" "/Users/btofel/workspace/package-operator/.cache/image/package-operator-manager/package-operator-manager"
exec: cp "-a" "config/images/remote-phase-manager.Containerfile" "/Users/btofel/workspace/package-operator/.cache/image/remote-phase-manager/Containerfile"
exec: cp "-a" "config/images/passwd" "/Users/btofel/workspace/package-operator/.cache/image/remote-phase-manager/passwd"
exec: cp "-a" "config/images/package-operator-manager.Containerfile" "/Users/btofel/workspace/package-operator/.cache/image/package-operator-manager/Containerfile"
exec: cp "-a" "config/images/passwd" "/Users/btofel/workspace/package-operator/.cache/image/package-operator-manager/passwd"
exec: cp "-a" "config/images/package-operator-webhook.Containerfile" "/Users/btofel/workspace/package-operator/.cache/image/package-operator-webhook/Containerfile"
exec: cp "-a" "config/images/passwd" "/Users/btofel/workspace/package-operator/.cache/image/package-operator-webhook/passwd"
STEP 1/2: FROM scratch
STEP 2/2: ADD . /package
STEP 1/2: FROM scratch
STEP 2/2: ADD . /package
--> Using cache a6e200792350a00a71ed97e3c980239d209e7e4ca557735d943594db1a74f8e8
COMMIT quay.io/package-operator/test-stub-package:f3f48ec
STEP 1/6: FROM scratch
--> a6e20079235
Successfully tagged quay.io/package-operator/test-stub-package:f3f48ec
STEP 2/6: WORKDIR /
a6e200792350a00a71ed97e3c980239d209e7e4ca557735d943594db1a74f8e8
--> Using cache e52c68c32cfab410b76b9c362f52f08596978f84a4e4409338d96040f7a261fa
--> e52c68c32cf
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
STEP 3/6: COPY passwd /etc/passwd
--> Using cache 89d43a8b8b749257ffd5ce52ca456002b5dbb660946c80a532afafc357a5ab12
COMMIT quay.io/package-operator/package-operator-package:f3f48ec
--> 89d43a8b8b7
Successfully tagged quay.io/package-operator/package-operator-package:f3f48ec
89d43a8b8b749257ffd5ce52ca456002b5dbb660946c80a532afafc357a5ab12
--> Using cache 108496fe505b4020876ef1b815c21a00055e53c679360733c440476daef0043d
--> 108496fe505
STEP 4/6: COPY test-stub /
STEP 1/6: FROM scratch
STEP 1/6: FROM scratch
STEP 2/6: WORKDIR /
STEP 2/6: WORKDIR /
STEP 1/6: FROM scratch
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
STEP 2/6: WORKDIR /
--> Using cache e52c68c32cfab410b76b9c362f52f08596978f84a4e4409338d96040f7a261fa
--> e52c68c32cf
--> Using cache e52c68c32cfab410b76b9c362f52f08596978f84a4e4409338d96040f7a261fa
--> e52c68c32cf
STEP 3/6: COPY passwd /etc/passwd
STEP 3/6: COPY passwd /etc/passwd
--> Using cache e52c68c32cfab410b76b9c362f52f08596978f84a4e4409338d96040f7a261fa
--> e52c68c32cf
STEP 3/6: COPY passwd /etc/passwd
--> Using cache ee5f3331b9ac6ee77e332f09d940fb972fcad314e39b10f9e4e19a6d18db4ac4
--> ee5f3331b9a
STEP 5/6: USER "noroot"
--> Using cache 108496fe505b4020876ef1b815c21a00055e53c679360733c440476daef0043d
--> 108496fe505
STEP 4/6: COPY package-operator-manager /
--> Using cache 108496fe505b4020876ef1b815c21a00055e53c679360733c440476daef0043d
--> 108496fe505
STEP 4/6: COPY package-operator-webhook /
--> Using cache 108496fe505b4020876ef1b815c21a00055e53c679360733c440476daef0043d
--> 108496fe505
STEP 4/6: COPY remote-phase-manager /
--> Using cache edca6021af57451586842f42044f0d9a0dc3187ed6aaeead526041c09ce1b0e7
--> edca6021af5
STEP 6/6: ENTRYPOINT ["/test-stub"]
--> Using cache ed435bab8d64ab903ad694739fdeab4f4cf170d565dffaddd88560dfc6ea40e1
COMMIT quay.io/package-operator/test-stub:f3f48ec
--> ed435bab8d6
Successfully tagged quay.io/package-operator/test-stub:f3f48ec
ed435bab8d64ab903ad694739fdeab4f4cf170d565dffaddd88560dfc6ea40e1
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
--> Using cache c112e1df33f5045b22f5e149361be6c5ade2211b41af35936b7147bb64ad3846
--> c112e1df33f
STEP 5/6: USER "noroot"
--> Using cache aa541b27cbb7067302b08fb70cbddb9a4bacfd3648ab6881b32348ea95c909d3
--> aa541b27cbb
STEP 5/6: USER "noroot"
--> Using cache ac9c4c07cc696018995cfa7de88835574b142c29c8eb49300404ba816cb42d5c
--> ac9c4c07cc6
STEP 5/6: USER "noroot"
--> Using cache b0c2d093f90240aec12ad7b1d4d8a1a1653356a408f71d619a949c767fa8df7d
--> b0c2d093f90
STEP 6/6: ENTRYPOINT ["/remote-phase-manager"]
--> Using cache 5434d40110c2b420bcd97ce71b1e1a8746086901794f15b765b9a1b31141cf7a
--> 5434d40110c
STEP 6/6: ENTRYPOINT ["/package-operator-manager"]
--> Using cache e8ce10ea59844a9395bcb5e2144069f0e729a7bf1472007ed155c7e6dae622a1
--> e8ce10ea598
STEP 6/6: ENTRYPOINT ["/package-operator-webhook"]
--> Using cache 482213d37006f0188ed48877a8e700408b819757606d29c297e3d3517c735ca3
COMMIT quay.io/package-operator/remote-phase-manager:f3f48ec
--> 482213d3700
Successfully tagged quay.io/package-operator/remote-phase-manager:f3f48ec
482213d37006f0188ed48877a8e700408b819757606d29c297e3d3517c735ca3
--> Using cache fd8a72359f58d1bcaab6a9772ee02fe6304d89d2c55c03d8f95c32b18a1aea57
COMMIT quay.io/package-operator/package-operator-manager:f3f48ec
--> fd8a72359f5
Successfully tagged quay.io/package-operator/package-operator-manager:f3f48ec
--> Using cache 71188c2f69a42833649ba100053d91452f3629dea3cd3527b6055883541445b4
COMMIT quay.io/package-operator/package-operator-webhook:f3f48ec
fd8a72359f58d1bcaab6a9772ee02fe6304d89d2c55c03d8f95c32b18a1aea57
--> 71188c2f69a
Successfully tagged quay.io/package-operator/package-operator-webhook:f3f48ec
71188c2f69a42833649ba100053d91452f3629dea3cd3527b6055883541445b4
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Running dependency: main.Generate.SelfBootstrapJob
----------------------------
loaded images into kind cluster:
quay.io/package-operator/package-operator-manager:f3f48ec
quay.io/package-operator/package-operator-webhook:f3f48ec
quay.io/package-operator/remote-phase-manager:f3f48ec
quay.io/package-operator/test-stub:f3f48ec
quay.io/package-operator/test-stub-package:f3f48ec
quay.io/package-operator/package-operator-package:f3f48ec
----------------------------
2022/11/30 19:25:52 "level"=0 "msg"="waiting 2m0s on apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /clusterobjectdeployments.package-operator.run to report condition \"Established\"=\"True\"..."
2022/11/30 19:25:54 "level"=0 "msg"="waiting 2m0s on apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /clusterobjectsetphases.package-operator.run to report condition \"Established\"=\"True\"..."
2022/11/30 19:25:55 "level"=0 "msg"="waiting 2m0s on apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /clusterobjectsets.package-operator.run to report condition \"Established\"=\"True\"..."
2022/11/30 19:25:56 "level"=0 "msg"="waiting 2m0s on apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /clusterpackages.package-operator.run to report condition \"Established\"=\"True\"..."
2022/11/30 19:25:57 "level"=0 "msg"="waiting 2m0s on apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /objectdeployments.package-operator.run to report condition \"Established\"=\"True\"..."
2022/11/30 19:25:58 "level"=0 "msg"="waiting 2m0s on apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /objectsetphases.package-operator.run to report condition \"Established\"=\"True\"..."
2022/11/30 19:25:59 "level"=0 "msg"="waiting 2m0s on apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /objectsets.package-operator.run to report condition \"Established\"=\"True\"..."
2022/11/30 19:26:00 "level"=0 "msg"="waiting 2m0s on apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /packages.package-operator.run to report condition \"Established\"=\"True\"..."
2022/11/30 19:26:01 "level"=0 "msg"="waiting 2m0s on apps/v1, Kind=Deployment package-operator-system/package-operator-manager to report condition \"Available\"=\"True\"..."
Error: deploying: deploy package-operator-manager: waiting for object: timed out waiting for the condition
```

**Comment by thetechnick** [comment]
Hey, sorry for the late reply.
end-of-the-year-marathon is hitting hard :)

Looks like you are not using latest `main`, we have changed the default tag format...
What OS are you running on and whats the version of podman (`podman info`) you are running?

**Comment by bentito** [comment]
okay I stashed any changes I had, fetched and pulled main. Now I get this error:

```bash
package-operator main $ ./mage dev:teardown && ./mage dev:deploy
panic: git describe: exit status 128

goroutine 1 [running]:
main.(*builder).init(0x2c61700)
	/Users/btofel/workspace/package-operator/magefile.go:547 +0x1b3
main.init.0()
	/Users/btofel/workspace/package-operator/magefile.go:112 +0x18b
```
which is because:
```bash
package-operator main $ git describe --tags
fatal: No names found, cannot describe anything
```

**Comment by thetechnick** [comment]
closing as stale.
A lot has happened over the last months.
Please reopen if the issue persists.
